### ISSUE TITLE
T-TWR Plus Rev 2.0

### ISSUE THREAD

**Issue by TechMindsYT** [erstec/APRS-ESP#47]
Hi all, I've tried using the pre-built binary and compiling but doesnt appear to work.

Using Platformio Terminal I see this:

        Connected!
EEPROM Check FFh=0h(644Byte)
Config EEPROM Error!
Applying Factory Default configuration!
Save EEPROM ChkSUM=25
E (3051) SPIFFS: mount failed, -10025

and then after a reboot I get:

EEPROM Check 25h=25h(644Byte)
SA868 Init
RF Modem powered up
AT+DMOSETGROUP=1,144.8000,144.8000,0000,1,0000
SA Answer Error
SA868 Init

Could anyone confirm if the T-TWR Plus Rev 2.0 is supported?

Thanks

**Comment by erstec** [comment]
There is NO SUPPORT for T-TWR 1.4 or 2.0 which uses ESP32S3. It need to be implemented.
All binaries in repo are for ESP32

**Comment by TechMindsYT** [comment]
I actually managed to get the display working and the http server is now accessible by changing some of the pin outs. GPS doesnt appear to get a lock, or its a pin out issue. I will continue to investigate. thanks

**Comment by erstec** [comment]
There is nothing to investigate, unfortunately.
ESP32S3 ADC/DAC was not implemented at all, so even if you manage all pin definitions, which are very different between T-TWR and T-TWR 2.0 no actual APRS signal will be emitted or decoded.

T-TWR support you mentioned is a draft for exactly T-TWR board, not T-TWR 2.0

**Comment by TechMindsYT** [comment]
Okay, thanks for confirming. You have an awesome project and I wanted to promote it using the boards I have here. Thanks so much for your hard work, I will order the parts needed so I can demonstrate your project. 
Thanks,
Matt M0DQW

**Comment by erstec** [comment]
Thank you,
What parts you want to order? To build/assemble "original" (non T-TWR) hardware?

**Comment by erstec** [comment]
@TechMindsYT 
If you mean what I asked, don't do that, if you own T-TWR2.0 ofc.
Contact me on Discord or email, I'll tell you how to make it (T-TWR2.0) "suitable" and not spend so much time and resources, then you can choose which way to move forward.

**Comment by TechMindsYT** [comment]
Thanks for the reply, if I can use my existing T-TWR Plus Rev 2.0 boards that would be awesome, but I don't mind buying either the original T-TWR board or the components, which ever is cheapest and quickest to demonstrate the project working. I have sent you a Friend Request on discord. Thanks, Matt

**Comment by erstec** [comment]
> Thanks for the reply, if I can use my existing T-TWR Plus Rev 2.0 boards that would be awesome, but I don't mind buying either the original T-TWR board or the components, which ever is cheapest and quickest to demonstrate the project working. I have sent you a Friend Request on discord. Thanks, Matt

Yes you can, with modifications.
I don't see your FR on Discord, my username is volwerene, as stated in my profile description. Or give me yours.
