### ISSUE TITLE
Multi-line packets are forwarded by the igate, allowing command injection attacks

### ISSUE THREAD

**Issue by hessu** [erstec/APRS-ESP#48]
https://github.com/erstec/APRS-ESP/blob/706c4cc254fef4fd7adc628901ed52db4b869696/src/igate.cpp#L76

APRS packets are only supposed to contain a single line of data. If a packet containing multiple lines of data (with some CR LF sequences in there), this igate now forwards all of those lines to the APRS-IS server. It generates the packet header for the first line it sends, but the additional lines will be forwarded unmodified, without header of any sort, and may contain additional headers, or anything else.

The second line in the received packet could just as well be an APRS-IS server command, such as `#filter p/N` which would suddenly cause the igate to receive a lot of packets from the APRS-IS server.

From https://github.com/hessu/aprsc/blob/main/doc/IGATE-HINTS.md:

> Please do not modify packet data. Do not trim spaces from the end, do not remove non-ASCII bytes such as 0x1C or 0x00. Just send everything on the first line, up to the newline (either first CR or LF character seen in packet).

Stop sending at the first CR *or* LF character in the packet, and send a CR LF sequence at the end of that line.

Thanks!

**Comment by erstec** [comment]
Thank you for notice!
Fixed by https://github.com/erstec/APRS-ESP/pull/49
